Makefile
nsjail.h

This lets us undefine any built-in gcc macro. Otherwise, a redefinition
from the command line occurs and a warning is thrown, breaking the build
(due to -Werror).

Move definition of _FORTIFY_SOURCE to nsjail.h

---

.gitmodules
Makefile
cmdline.c
common.h
sandbox.c

Hi,
This patch adds support for Kafel library, which is an easier way to specify syscall filtering policies.
Best regards,
Wiktor

Kafel support

---

log.c

The terminal behind fd 2 might be owned by root and can't be opened by the user.
This happens e.g. if you ssh to a server as root and su to the user.

Don't try to open /proc/self/fd/2 as we might not have permission

---

cmdline.c
common.h
user.c

Introduces the new options uid_mapping and gid_mapping that specify
arbitrary custom mappings. If these options are used, nsjail will
use newuidmap/newgidmap to write the map files.

Support more complex uid and gid mappings

---

cmdline.c
common.h
mount.c

The change introduces a new flag --pivot_root_only that, if set, will skip the chroot in mount.c.
This allows the process inside of nsjail to create new nested usernamespaces.

Option to skip chroot (for nested user namespaces)

---

cmdline.c
cmdline.h

This is in preparation for other networking models. The current option
names were very generic, and without namespacing them we could end up
with some very confusing naming.
Also some miscellaneous indentation fixes.

Deprecate current iface/macvlan options.

---

Dockerfile
Makefile

Kafel submodule will be automatically initialized if not done manually before invoking `make`.
Just 2 commands needed now:
$ git clone https://github.com/google/nsjail.git
$ make -C nsjail

Simplify cloning/building.

---

Dockerfile
README.md

To build the latest nsjail in docker, I think several packages are missing.
Let me update Dockerfile to install such packages.
Also, let me do some clean up.
- update and install become different lines.
- move -y to the beginning.
- make installed packages alphabetical order.

Fix Dockerfile to make it built with current Makefile.

---

cmdline.c
common.h
config.c
subproc.c

This is a bit of a niche use case, but sometimes I don't want the binary's argv[0] to be the binary's name.
Hopefully this change isn't too contentious. I wasn't sure about specifying an extra setting in the protobuf, but let me know if you would like one.

Add an --exec_file argument to allow argv[0] to differ from the binary being exec'd.

---

cmdline.c
common.h
config.c
config.proto
log.c

(this patch is crazy, but so is systemd so bear with me)
In some situations, setting --log to /proc/self/fd/# is not sufficient to log out to a different FD. For instance, if a master process passes its stderr to the child nsjail process as fd 3, the nsjail child may not always be able to log to /proc/self/fd/3, e.g. if the master process is running under systemd, whose /proc/self/fd/2 is actually a socket and not a pipe. However, having nsjail write to fd 3 directly is fine and there's no other good way to handle this situation.

Add an extra log_fd argument to specify an FD to log to.

---

Dockerfile

Implement best practices for Dockerfiles as per the official
documentation:
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
Reduces image size from 451.6MB to 404.9MB.

Refactor using current official Dockerfile best practices

---

configs/bash-with-fake-geteuid.cfg

The error code 1337 seems to have been removed accidentally in the file `configs/bash-with-fake-geteuid.cfg`. It turns out to be inconsistent with the description: 
> ... Also, __NR_geteuid returns -1337 value, which /usr/bin/id will show as euid=4294965959. ...
This commit adds it back.

Add back ERRNO(1337) for example config

---

Dockerfile

Before the fix the build ends up somewhere with:
> sys/capability.h: No such file or directory

Fix dockerfile: add libcap-dev install

---

Makefile

I reverted one of the changes as it caused the following error on Ubuntu 16.04:
```
g++ -O2 -c -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -Wformat -Wformat=2 -Wformat-security -fPIE -Wno-format-nonliteral -Wall -Wextra -Werror -Ikafel/include -pthread -I/usr/local/include -std=c++11 -Wno-unused -Wno-unused-parameter config.cc -o config.o
config.cc:45:23: fatal error: config.pb.h: No such file or directory
compilation terminated.
Makefile:66: recipe for target 'config.o' failed
make: *** [config.o] Error 1
```

Adding the mistakenly removed line to the makefile

---

log.c
mount.c
nsjail.c
subproc.c

For ease of distinguishing errors coming from a program executed by
nsjail and errors from nsjail, let me change nsjail error exit
status code to 0xff instead of 1.
I think most of programs use EXIT_FAILURE (i.e. 1) as a default
error exit status code.

Use 0xff as nsjail error exit status code.

---

sandbox.c

Hiho,
This is just small refactor of sandbox.c, it shouldn't change any functionality.
Btw is there any real purpose of having `static bool sandboxPrepareAndCommit` and `bool sandboxApply`? Should I change `sandboxPrepareAndCommit` into `sandboxApply`?

sandbox.c: small refactor

---

nsjail.1

Adjust rlimit_* options to match command line --help output.
Add --really_quiet option.
And some clean up:
Remove 'See Also' section that only references a non-existent
info page that is a relic of using help2man for initial manual
page generation.

manpage: tweak for recent options changes

---

caps.c

Restore compatibility with 3.x kernels by not requiring CAP_AUDIT_READ
if not defined in kernel header file
This reverts commit 7820553cb9296b5f1a3137153948db45309aa6b1.
Conflicts:
caps.c
contain.h

Revert "caps: define CAP_AUDIT_READ if not defined"

---

subproc.c

Fixes "bus error" crashes on aarch64 caused by alignment faults.
On aarch64, the stack pointer needs to be 16-byte aligned; use gcc
builtin macro `__BIGGEST_ALIGNMENT__` to specify a stack alignment
suitable for each platform.

align stack for child process

---

README.md
cgroup.c
cmdline.c
config.cc
config.proto
nsjail.1
nsjail.h

Hi,
This patch adds support for cgroup's net_cls subsystem.
We can set class identifiers to network packets that occurred  in the jail and use it for traffic control and filtering.
Best regards,

Support cgroup net_cls subsystem

---

uts.c

While analyzing source code I noticed that for UTS namespace is performed twice, before and after log statement.

Remove redundant check if UTS namespace is enabled

---

README.md
nsjail.1

Also, move the --cap option description so that it follows the --keep-caps option, which matches the --help output and seems logical.

nsjail.1: update for new options.

---

nsjail.1

Added --symlink/-s option.
Removed --tmpfs_size option.
Changed --cpu_mount, --cpu_parent to
--cgroup_cpu_mount, --cgroup_cpu_parent.
Adjustments to match README.

nsjail.1: update manpage to match README

---

util.h

In 25a7791d return type of writeToFD() was changed from `ssize_t` to `bool`, but header wasn't updated.

fix writeToFD() return type in declaration

---

Dockerfile

The example compiling Docker in the readme didn't work, but this fixes it.
It looks like the Makefile treats libnl as optional, but based on the include in net.cc, it appears to be a hard requirement. Let me know if it would be useful to also modify the makefile to fail hard if libnl is mssing instead of warning and continuing.

Fixed missing dependency on libnl-route-3-dev

---

cmdline.cc

Fixes #108 - not being able to set `cgroup_cpu_mount` from CLI.
As can be see further in the code, the proper id for `cgroup_cpu_mount` option is 0x832:
```c
case 0x832:
nsjconf->cgroup_cpu_mount = optarg;
break;
```

Fix #108 - missing cgroup_cpu_mount option setting

---

Makefile
cgroup2.cc
cgroup2.h
cmdline.cc
config.cc
config.proto
nsjail.1
nsjail.h
subproc.cc

Add cgroup v2 support for memory max, cpu max and pids max. 
I have mirrored the API from cgroup v1, using most of the previous configuration options that applied. The major difference is that it now uses a global mount for the configuration (again defaulting to `/sys/fs/cgroup`) instead of one per resource. Also add a flag to enable cgroup v2.
Currently it creates a cgroup from the mount point as:
```
"${MOUNT}/NSJAIL.${PID}"
```
It will then update the `memory.max`, `cpu.max` and `pids.max` as per the configuration.
There is currently no support for `net_cls` using cgroup v2, so I am unable to include it.
Closes #65

[cgroup-v2] support cgroup v2 for mem, cpu and pids

---

cmdline.cc
config.cc
config.proto
contain.cc
nsjail.1
nsjail.h

It might be useful to disable the default `rlimits` set by NSJail and instead use `cgroups` to control a processes access to these resources. 
This flag will prevent any rlimit values being set, and instead default the values to whatever the parent has set, as per http://man7.org/linux/man-pages/man2/getrlimit.2.html

Add flag to disable rlimits

---

config.proto

The default `rlimit_stack` value is 1048576. However, this value is in MiB and so is later multiplied by 1024*1024 in https://github.com/google/nsjail/blob/b3d544d155f5d1543dce1bd3e5327ef41583815a/config.cc#L162-L163 and it ends up as a limit of 1 TB for the stack size.
This PR changes it to 8 MB which is a more sane default or, at least I took it from my virtual machine's ulimits:
```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31175
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX …
```

Fix default rlimit_stack value

---

subproc.cc

Starting with nsjail::listenMode update to pipe socket traffic [commit 273ce6bc846b7325c7f0915067c54bf8cf6f5654], a pipe file descriptor is passed as connsock parameter when calling net::limitConns and also as sock parameter when calling addProc in subproc::runChild.
This breaks net::limitConns because pid.remote_addr and also local variable addr are left uninitialized despite net::connToText calls when counting number of existing network connections from the same peer.
The subsequent correction to fetch remote address [commit 2cf562160d308f9b5cca767a2459332f2041b41c] made the bug even more interesting, since the loop in net::limitConns now compares unsanitized content of stack with network addresses of already connected clients.

fix non-functional max_conns_per_ip

---

Makefile
user.cc

Currently `newuidmap` and `newgidmap` paths are hardcoded to `/usr/bin/...`. Some Linux distributions do not follow the conventional FHS and need to patch the source code before building:
https://github.com/NixOS/nixpkgs/blob/f72a67f7d8a1bcca82d3961c73c7f44f264e3548/pkgs/tools/security/nsjail/default.nix#L18-L20
This PR allows to configure `newuidmap` and `newgidmap` paths through a make flag:
```sh
make USER_DEFINES='-DNEWUIDMAP_PATH=\"/path/to/newuidmap\" -DNEWGIDMAP_PATH=\"/path/to/newgidmap\"'
```

Build-time config of newuidmap and newgidmap paths

---

config.proto

This commit fixes the incorrect cgroups_mem_max unit described in a config.proto comment.
We do not perform any calculations on this value and we don't specify the values unit (k/M/G) when writing to memory cgroup controller files, so the value is specified in bytes.

Fixes #146: cgroups_mem_max unit in config.proto

---

nsjail.cc

Just use explicit `std::make_tuple` constructors.
Not sure if you care about building nsjail on older compilers, but this commit enables it e.g. on gcc 5.4.0, which is default on ubuntu 16.04

Fix compilation errors on old gcc (5.4.0)

---

Makefile

We're building nsjail for a few different targets (fedora, centos) that don't include `which` in their standard/base docker images. This small change removes the need for installing another build time dependency by relying on the shell's `command` func instead.
I'm not sure if `command` is a bashism and may not be portable but I think with nsjail's ties to Linux specific features that this is safe for most Linux distros.

remove build dependency on which

---

README.md
cmdline.cc
config.cc
config.proto
net.cc
nsjail.1
nsjail.h

This PR adds the `max_conns` option for both the proto2 config file and the cmdline.
`max_conns` limits the total number of concurrent open connections while in `LISTEN` mode.

net: add support for max_conns

---

README.md
cmdline.cc

The default value for cgroup_cpu_mount is `/sys/fs/cgroup/cpu`.
https://github.com/google/nsjail/blob/645eabd862e4eb20ec70a387fb7d50ecbc613f6e/cmdline.cc#L440

Fix a typo in command line description

---

subproc.cc

Compilation failed due to an extra #define (line 63) in subproc.cc. Fixed.

Fixed macro in subproc.cc

---

cgroup.cc

The CFS CPU limit applied by nsjail must be less than or equal to the limit applied by `cgroup_cpu_parent` and its ancestors.
If the `cpu.cfs_period_us` of any ancestor cgroups is less than `1000000` (nsjail's value), the CPU quota for the new nsjail cgroup can be temporarily greater than its ancestors, even if the `cgroup_cpu_ms` is less than all ancestors. This results in an `EINVAL` when writing `cpu.cfs_quota_us`.
We can avoid this issue by writing `cpu.cfs_period_us` before `cpu.cfs_quota_us`.

write CPU CFS period before quota in cgroup1

---

cmdline.cc
config.cc
config.proto
mnt.cc
nsjail.h

When enabling mount namespace, nsjail uses pivot_root system call to un-mount old root.        
In certain cases this operation is forbidden. There are systems (mainly embedded) that keep their root file system in RAM,
when initially loaded by the kernel (e.g. initramfs, initrd), and there is no other file system that is mounted on top of it. In such systems, there is option to pivot_root!
For more information, see http://kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt, under "What is initramfs?"
I suggest an alternative that comes from the article above, and it is more of a switch_root implementation.
Instead of un-mounting the old initramfs, it is over mounted by moving the new root to it. This way, we prevent the process from hacking its way back into the old root.

Use switchroot

---

README.md
cmdline.cc
nsjail.1

In https://github.com/google/nsjail/commit/9b8d91bd7fda783cd21b26063e060b0c1b0daeba  the default for `rlimit_as` was increased to 4096 MB, but old default remained in the man page, readme, etc. This patch corrects those spots with the right value.

The default rlimit_as value is 4096, not 512.

---

README.md
cgroup.cc
cgroup2.cc
cmdline.cc
config.cc
config.proto
nsjail.1
nsjail.h

Currently, `cgroup_mem_memsw_max` is only used with cgroup v1. The option is silently ignored with cgroup v2.
Because there is no way to limit swap + memory usage in cgroup v2, we write `cgroup_mem_memsw_max - cgroup_mem_max` to `memory.swap.max`.

support cgroup_mem_memsw_max in cgroup2

---

subproc.cc

`struct clone_args` (for clone3) only has `set_tid` and `set_tid_size` in Linux 5.5 and `cgroup` in Linux 5.7. This breaks builds based on the ubuntu:20.04 docker image (which ships with 5.4 headers)
Example Dockerfile snippet:
```
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get install -y \
autoconf \
bison \
flex \
gcc \
g++ \
git \
libprotobuf-dev \
libnl-route-3-dev \
libtool \
make \
pkg-config \
protobuf-compiler \
uidmap \
&& \
rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/google/nsjail.git && \
cd nsjail && \
make -j8
```
Fails like:
```
#6 2.769 subproc.cc: In function 'pid_t subproc::cloneProc(uintptr_t, int)':
#6 2.769 subproc.cc:541:2: error: 'clone_args' has no non-static data member named 'set_tid'
#6 2.769   541 |  };
#6 …
```

Fix compile using `FROM ubuntu:20.04`

---

cmdline.cc
config.cc
config.proto
contain.cc
nsjail.h

Implemented via `prctl(PR_SET_TSC, PR_TSC_SIGSEGV, ...)`. May be useful for CPU side-channel challenges :)

Add `disable_tsc` option

---

README.md
cmdline.cc

Seems there were even more options than `--disable_tsc` missing from it!
FYI: There's some "diff-noise" because I pasted the updated usage in the readme with tabs -> spaces because the rest of the readme uses spaces. But I can change it back to tabs if you prefer. Best to review with `--word-diff=color`.

Add more docs for disable_tsc + update README

---

README.md
cmdline.cc
config.cc
config.proto
nsjail.cc
nsjail.h
subproc.cc
subproc.h

Currently, we always kill children by sending them a SIGKILL signal in
case we've got a fatal signal. This is rather inflexible and forbids
some usecases where e.g. child process listen for specific signals to
shut down gracefully.
Add a new command configuration `--forward_signals` that allows the user
to opt-in to forwarding fatal signals to the child process.

Optionally forward fatal signals

---

Makefile

Otherwise kafel inherit's nsjail LDFLAGS, which isn't intended and causes build failures.

Unset LDFLAGS for kafel

---

cgroup2.cc
cgroup2.h
cmdline.cc
config.cc
config.proto
nsjail.cc
nsjail.h
util.cc
util.h

This commit adds extra setup when cgroupsv2 is enabled. In particular, we make sure that the root cgroup (whatever `cgroupv2_mount` is set to) has setup cgroup.subtree_control with the controllers we need.
If the necessary controller are not listed, we have to move all processes out of the root cgroup before we can change this (the 'no internal processes' rule: https://unix.stackexchange.com/a/713343). Currently this handles the case where the nsjail process is the only process in the cgroup. It seems like this would be relatively rare, but since nsjail is frequently the root process in a Docker container (e.g. for hosting CTF challenges), I think this case is common enough to make it worth implementing.
This also adds `--detect_cgroupv2`, which will attempt to detect whether …

Setup cgroup.subtree_control controllers when necessary in cgroupsv2

---

cgroup2.cc

This PR improves the error log message when Nsjail fails to write to the `/sys/fs/cgroup/cgroup.subtree_control` file when it attempts to setup the cgroupv2 configuration.
The previous message looked like this:
```
[E][2023-05-28T21:52:56+0000][8807] writeBufToFile():105 Couldn't write '7' bytes to file '/sys/fs/cgroup/cgroup.subtree_control' (fd='4'): Device or resource busy
[E][2023-05-28T21:52:56+0000][8807] enableCgroupSubtree():95 Could not apply '+memory' to cgroup.subtree_control in '/sys/fs/cgroup'. If you are running in Docker, nsjail MUST be the root process to use cgroups.
[E][2023-05-28T21:52:56+0000][8807] main():354 Couldn't setup parent cgroup (cgroupv2)
```
And it may be confusing to nsjail users because the nsjail may have already been running as real root with full …

cgroup2.cc: improve note about using Docker

---

config.cc
configs/bash-with-fake-geteuid.json

JSON is an easier to generate than TextProto in some environments, e.g. Jsonnet or Nix.
https://protobuf.dev/reference/cpp/api-docs/google.protobuf.util.json_util/

config: try to parse as ProtoJSON
